### PR TITLE
Remove print_debug and log_txt

### PR DESCRIPTION
**Pull request by taiga4112**

### CODE REVIEW

**Comment by taiga4112** [comment]
Here is an example project for verifying print_log func.

```py
c = BaseComponent("c", space_size=1.0)
task1 = BaseTask("task1", default_work_amount=2.0)
task2 = BaseTask("task2", default_work_amount=2.0)
auto_task2 = BaseTask("auto_task2", auto_task=True, default_work_amount=1.0)
task2.append_input_task(auto_task2)
# auto_task2.append_input_task(task2) # backward
task3 = BaseTask("task3", default_work_amount=2.0)
auto_task3 = BaseTask("auto_task3", auto_task=True, default_work_amount=1.0)
task3.append_input_task(auto_task3)
# auto_task3.append_input_task(task3) # backward
workflow = BaseWorkflow([task1, task2, task3, auto_task2, auto_task3])
c.extend_targeted_task_list([task1, task2, task3, auto_task2, auto_task3])
product = BaseProduct([c])

# BaseTeams in BaseOrganization
team = BaseTeam("team")
team.extend_targeted_task_list([task1, task2, task3])

# BaseWorkers in each BaseTeam
w1 = BaseWorker("w1", team_id=team.ID, absence_time_list=[1])
w1.workamount_skill_mean_map = {
    task1.name: 1.0,
}
team.add_worker(w1)

w11 = BaseWorker("w11", team_id=team.ID, absence_time_list=[0,1])
w11.workamount_skill_mean_map = {
    task1.name: 1.0,
}
team.add_worker(w11)

w2 = BaseWorker("w2", team_id=team.ID)
w2.workamount_skill_mean_map = {
    task2.name: 1.0,
}
team.add_worker(w2)
w3 = BaseWorker("w3", team_id=team.ID, absence_time_list=[3])
w3.workamount_skill_mean_map = {
    task3.name: 1.0,
}
team.add_worker(w3)

project = BaseProject(
    init_datetime=datetime.datetime(2020, 4, 1, 8, 0, 0),
    unit_timedelta=datetime.timedelta(days=1),
    product=product,
    workflow=workflow,
    organization=BaseOrganization(team_list=[team]),
)
```

**Comment by taiga4112** [comment]
Only printing of product log.

```py
project.product.print_all_log_in_chronological_order()
```

> TIME:  0
> 7d57fad5-ef72-4bb0-9f69-fb5db89b67fd c BaseComponentState.WORKING None
> TIME:  1
> 7d57fad5-ef72-4bb0-9f69-fb5db89b67fd c BaseComponentState.WORKING None
> TIME:  2
> 7d57fad5-ef72-4bb0-9f69-fb5db89b67fd c BaseComponentState.READY None
> TIME:  3
> 7d57fad5-ef72-4bb0-9f69-fb5db89b67fd c BaseComponentState.WORKING None
> TIME:  4
> 7d57fad5-ef72-4bb0-9f69-fb5db89b67fd c BaseComponentState.WORKING None

**Comment by taiga4112** [comment]
Only printing of workflow log.

```py
project.workflow.print_all_log_in_chronological_order()
```

**Comment by taiga4112** [comment]
Only printing of organization log.

```py
project.organization.print_all_log_in_chronological_order()
```

**Comment by yuiokubo** [comment]
> project.product.print_all_log_in_chronological_order() ↓ 
>
>`TIME: 0 7d57fad5-ef72-4bb0-9f69-fb5db89b67fd c BaseComponentState.WORKING None` `TIME: 1 7d57fad5-ef72-4bb0-9f69-fb5db89b67fd c BaseComponentState.WORKING None` `TIME: 2 7d57fad5-ef72-4bb0-9f69-fb5db89b67fd c BaseComponentState.READY None` `TIME: 3 7d57fad5-ef72-4bb0-9f69-fb5db89b67fd c BaseComponentState.WORKING None` `TIME: 4 7d57fad5-ef72-4bb0-9f69-fb5db89b67fd c BaseComponentState.WORKING None`
> 
> What is the meaning of None next to the WORKING?

------------
> I want to display the remaining work amount for each task.

**Comment by taiga4112** [comment]
> project.product.print_all_log_in_chronological_order() ↓ `TIME: 0 7d57fad5-ef72-4bb0-9f69-fb5db89b67fd c BaseComponentState.WORKING None` `TIME: 1 7d57fad5-ef72-4bb0-9f69-fb5db89b67fd c BaseComponentState.WORKING None` `TIME: 2 7d57fad5-ef72-4bb0-9f69-fb5db89b67fd c BaseComponentState.READY None` `TIME: 3 7d57fad5-ef72-4bb0-9f69-fb5db89b67fd c BaseComponentState.WORKING None` `TIME: 4 7d57fad5-ef72-4bb0-9f69-fb5db89b67fd c BaseComponentState.WORKING None`
> 
> What is the meaning of None next to the WORKING?

Check the function of [`print_log()`](https://github.com/pDESy/pDESy/blob/74b039682f792720b16c2664f1b13722abc8e47c/pDESy/model/base_component.py#L411).

**Comment by taiga4112** [comment]
> I want to display the remaining work amount for each task.

OK. I will try this problem.

**Review by yuiokubo — APPROVED** [review]

**Pull request merged**
